package co.edu.unicauca.DesignPatterns.domain.entities;

/** Estados de alto nivel del proceso académico. */
public enum EstadoProyecto {
    PRESENTADO_AL_COORDINADOR,
    EN_EVALUACION_COMITE,
    CORRECCIONES_COMITE,
    ACEPTADO_POR_COMITE,
    RECHAZADO_POR_COMITE,
    ESCRIBIENDO_ANTEPROYECTO,
    PRESENTADO_JEFATURA,
    EVALUACION_DEPARTAMENTO,
    EVALUADOR_PIDE_CORRECCIONES,
    EVALUADOR_ACEPTA,
    EVALUADOR_RECHAZA,
    EN_DESARROLLO,
    PRORROGA_SOLICITADA,
    FINALIZADO_MONOGRAFIA,
    FECHA_SUSTENTACION_FIJADA,
    PROYECTO_APROBADO,
    PROYECTO_RECHAZADO
}
